# dockerversion: '3.9'

services:
  postgis:
    image: postgis/postgis:16-3.4          # stable, recent version
    container_name: postgis_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - vsol:/var/lib/postgresql/data
      - ./data:/data                     # for CSV import later
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  martin:
    image: ghcr.io/maplibre/martin:latest   # official image
    container_name: martin_server
    restart: unless-stopped
    env_file:
      - .env                                 # expose DB vars to Martin
    ports:
      - "3000:3000"
    volumes:
      - ./martin-config.yml:/config.yml:ro
    depends_on:
      postgis:
        condition: service_healthy
    command: --config /config.yml

  tileserver-gl:
    image: maptiler/tileserver-gl:latest
    container_name: tileserver_gl
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./tileserver:/tileserver:ro       # config.json + styles/
      - ./data/mbtiles:/data/mbtiles:ro  # mbtiles files
    command: --config /tileserver/config.json --verbose

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    env_file: 
      - .env    
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgis
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - martin
      - tileserver-gl    

volumes:
  vsol: # name of the volume in docker